export * from "./NavBar";
export * from "./Footer";
export * from "./Banner";
export * from "./Carousel";
export * from "./Info";
export * from "./FixedButton";
export * from "./MyButton";
export * from "./Documentospdf";
export * from "./VideosDocumentos";
